### ISSUE TITLE
Content : Next Permutation 

### ISSUE THREAD

**Issue by NEERAJAP2001** [TesseractCoding/NeoAlgo-Docs#26]
Description
Add the article for ```Next Permutation```. The basic layout for the article should be:

What is Next Permutation?
The explanation for Next Permutation
Algorithmic Steps
Code (Use C++/Java and Python; At least two languages should be present and pick up code from NeoAlgo with apt credits to author)
Sample I/O
Time & Space Complexity
This article should be between 500-700 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

I will be using my code itself ( merged in neoalgo repo).

**Comment by NEERAJAP2001** [comment]
@HarshCasper is that okay?
Can I start working?

**Comment by HarshCasper** [comment]
For sure @NEERAJAP2001 

Few instructions: 

- Install the Project locally. You need to use NodeJS and Yarn (Instructions are on README.md)
- Find the directory in `src` where this should ideally go. Let's say it goes in `mathematics`, so create a file in there named `next-permutation.md`
- Once you do that, go over to [sidebar.js](https://github.com/TesseractCoding/NeoAlgo-Docs/blob/main/sidebars.js) in your forked repo, and go over to [this line](https://github.com/TesseractCoding/NeoAlgo-Docs/blob/781088e0adbcebf313213e937ebe5ed21564bbd2/sidebars.js#L57) and add `mathematics/next-permutation.md`
- Always check the application build and see if your article is being correctly rendered on the local server

Let me know if you need more help with this. We would be glad to have you contribute!

**Comment by HarshCasper** [comment]
Heya - Hope you are working on this ✨  

We have just pushed some new features on the `main` so it would be great if you can pull the changes from the `main` branch, so that we don't run into any merge conflicts. 

Second, I have some important notes for you. While adding the articles, it would be preferred if you use the `mdx` file extension instead of `md`. `mdx` provides us to combine Markdown + React. And we will be using it for a good reason. 

First, we want to tab the codes like these: 

![image](https://user-images.githubusercontent.com/47351025/114029857-94458600-9897-11eb-99cf-a1a576301732.png)

Using standard markdown won't be beneficial for us. We can use some React Code to make it possible. Don't fret out if you don't know React. Here is an official [documentation](https://docusaurus.io/docs/markdown-features/code-blocks#multi-language-support-code-blocks) that you can refer to format the Code in separate tabs. Have a look and let me know if you are still in trouble. 

Also try to keep the I/O samples same for both the Code. If it requires minor altercations, feel free to do them. Thanks!

**Comment by NEERAJAP2001** [comment]
Hey, @HarshCasper I did not find code implementation of this problem ```next permutation``` in java or c++ ( in the NeoAlgo repo) how do I proceed? 
Is it fine If I add only for Python?

**Comment by HarshCasper** [comment]
> Hey, @HarshCasper I did not find code implementation of this problem `next permutation` in java or c++ ( in the NeoAlgo repo) how do I proceed?
> Is it fine If I add only for Python?

Yes
