### ISSUE TITLE
Sorting an array of 0s ,1s and 2s 

### ISSUE THREAD

**Issue by soumik2012** [TesseractCoding/NeoAlgo-Docs#32]
## 📚 Documentation

Given an array of size N containing only 0s, 1s, and 2s; sort the array in ascending order. the language is using python

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Input: 
Enter the Number:
0 2 1 2 0
Output:
0 0 1 2 2
Explanation:
0s 1s and 2s are segregated 
into ascending order

**Comment by HarshCasper** [comment]
Hi @geekymeeky   

Few instructions: 

- Install the Project locally. You need to use NodeJS and Yarn (Instructions are on README.md)
- Find the directory in `src` where this should ideally go. Let's say it goes in `competitive-coding`, so create a file in there named `sort-array.md`
- Once you do that, go over to [sidebar.js](https://github.com/TesseractCoding/NeoAlgo-Docs/blob/main/sidebars.js) in your forked repo, and go over to [this line](https://github.com/TesseractCoding/NeoAlgo-Docs/blob/781088e0adbcebf313213e937ebe5ed21564bbd2/sidebars.js#L81) and add `searching-algorithms/sort-array.md`
- Always check the application build and see if your article is being correctly rendered on the local server

Let me know if you need more help with this. We would be glad to have you contribute!

**Comment by HarshCasper** [comment]
Heya - Hope you are working on this ✨  

We have just pushed some new features on the `main` so it would be great if you can pull the changes from the `main` branch, so that we don't run into any merge conflicts. 

Second, I have some important notes for you. While adding the articles, it would be preferred if you use the `mdx` file extension instead of `md`. `mdx` provides us to combine Markdown + React. And we will be using it for a good reason. 

First, we want to tab the codes like these: 

![image](https://user-images.githubusercontent.com/47351025/114029857-94458600-9897-11eb-99cf-a1a576301732.png)

Using standard markdown won't be beneficial for us. We can use some React Code to make it possible. Don't fret out if you don't know React. Here is an official [documentation](https://docusaurus.io/docs/markdown-features/code-blocks#multi-language-support-code-blocks) that you can refer to format the Code in separate tabs. Have a look and let me know if you are still in trouble. 

Also try to keep the I/O samples same for both the Code. If it requires minor altercations, feel free to do them. Thanks!
