### ISSUE TITLE
Content: Bipartite Check

### ISSUE THREAD

**Issue by Jahnavi-Majji** [TesseractCoding/NeoAlgo-Docs#33]
Add the article for `Bipartite Check`. The basic layout for the article should be:

*  What is Bipartite Check?
* Explanation for Bipartite Check
* Algorithmic Steps
* Code (Use C++/Java and Python; At least two languages should be present and pick up code from NeoAlgo with apt credits to author)
* Sample I/O
* Time & Space Complexity

This article should be between 500-700 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

**Comment by HarshCasper** [comment]
Hi @Jahnavi-Majji  

Thanks for taking this up! I hope you spend sometime in understanding the directory structure and where to make the PR. If you are confused, check it right here: https://github.com/TesseractCoding/NeoAlgo-Docs/tree/main/docs/graph-algorithms

Create a file named `Bipartite-Check.md` and add the same on the sidebar. Please let me know if you face any difficulties and do check if your article is being rendered on the local server :+1:

**Comment by HarshCasper** [comment]
Heya - Hope you are working on this ✨  

We have just pushed some new features on the `main` so it would be great if you can pull the changes from the `main` branch, so that we don't run into any merge conflicts. 

Second, I have some important notes for you. While adding the articles, it would be preferred if you use the `mdx` file extension instead of `md`. `mdx` provides us to combine Markdown + React. And we will be using it for a good reason. 

First, we want to tab the codes like these: 

![image](https://user-images.githubusercontent.com/47351025/114029857-94458600-9897-11eb-99cf-a1a576301732.png)

Using standard markdown won't be beneficial for us. We can use some React Code to make it possible. Don't fret out if you don't know React. Here is an official [documentation](https://docusaurus.io/docs/markdown-features/code-blocks#multi-language-support-code-blocks) that you can refer to format the Code in separate tabs. Have a look and let me know if you are still in trouble. 

Also try to keep the I/O samples same for both the Code. If it requires minor altercations, feel free to do them. Thanks!

**Comment by Jahnavi-Majji** [comment]
Hey, @HarshCasper I have my `.mdx` file ready but I couldn't clone the repo. It's giving me an error. I am attaching it here for ref. Can you please look into this?
![Screenshot (80)](https://user-images.githubusercontent.com/74998474/114406121-e6064d00-9bc4-11eb-9a67-07a59d6a85c3.png)

**Comment by Jahnavi-Majji** [comment]
Hey, @HarshCasper I couldn't make a PR. It says that :

```
ERROR: Permission to TesseractCoding/NeoAlgo-Docs.git denied to Jahnavi-Majji.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
