### ISSUE TITLE
Content: Check if a linked list is palindromic or not using stacks

### ISSUE THREAD

**Issue by SAY-droid427** [TesseractCoding/NeoAlgo-Docs#38]
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by HarshCasper** [comment]
Heya - Hope you are working on this ✨  

We have just pushed some new features on the `main` so it would be great if you can pull the changes from the `main` branch, so that we don't run into any merge conflicts. 

Second, I have some important notes for you. While adding the articles, it would be preferred if you use the `mdx` file extension instead of `md`. `mdx` provides us to combine Markdown + React. And we will be using it for a good reason. 

First, we want to tab the codes like these: 

![image](https://user-images.githubusercontent.com/47351025/114029857-94458600-9897-11eb-99cf-a1a576301732.png)

Using standard markdown won't be beneficial for us. We can use some React Code to make it possible. Don't fret out if you don't know React. Here is an official [documentation](https://docusaurus.io/docs/markdown-features/code-blocks#multi-language-support-code-blocks) that you can refer to format the Code in separate tabs. Have a look and let me know if you are still in trouble. 

Also try to keep the I/O samples same for both the Code. If it requires minor altercations, feel free to do them. Thanks!
