### ISSUE TITLE
Template for the format of the documentation

### ISSUE THREAD

**Issue by nagasrihith608** [TesseractCoding/NeoAlgo-Docs#60]
## 🚀 Feature

I had written a .txt file where it is already formatted in the required format from Introduction to credits.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation
To help the contributors with the right format and also saves time  

This can be added as Contributors Template.

@HarshCasper please assign this issue to me.

**Comment by HarshCasper** [comment]
It is already in work here: https://github.com/TesseractCoding/NeoAlgo-Docs/issues/35 

Instead of this, can you work on converting our Contributor's Handbook [here](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit). 

Let me know if you would like to work on this under a `Level3` tag

**Comment by nagasrihith608** [comment]
@HarshCasper This is the issue I opened for Template
